services:
  - type: web
    name: streamflow-api
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL_AUTH
        sync: false
      - key: DATABASE_URL_USUARIOS
        sync: false
      - key: JWT_SECRET
        sync: false